/* ===========================
   01_schema_tables.sql
   SQL Server (MSSQL) için
   =========================== */

-- (Opsiyonel) Tekrar çalıştırabilmek için drop sırası:
IF OBJECT_ID('dbo.THESIS', 'U') IS NOT NULL DROP TABLE dbo.THESIS;
IF OBJECT_ID('dbo.INSTITUTE', 'U') IS NOT NULL DROP TABLE dbo.INSTITUTE;
IF OBJECT_ID('dbo.SUPERVISOR', 'U') IS NOT NULL DROP TABLE dbo.SUPERVISOR;
IF OBJECT_ID('dbo.UNIVERSITY', 'U') IS NOT NULL DROP TABLE dbo.UNIVERSITY;
IF OBJECT_ID('dbo.AUTHOR', 'U') IS NOT NULL DROP TABLE dbo.AUTHOR;
GO

/* ========== PARENT TABLOLAR ========== */

CREATE TABLE dbo.AUTHOR(
  A_ID INT IDENTITY(1,1) NOT NULL,
  A_NAME VARCHAR(50) NOT NULL,
  A_PHONE VARCHAR(15) NOT NULL,
  CONSTRAINT PK_AUTHOR PRIMARY KEY (A_ID)
);
GO

CREATE TABLE dbo.UNIVERSITY(
  UNI_ID INT IDENTITY(100,1) NOT NULL,
  UNI_NAME VARCHAR(100) NOT NULL,
  UNI_RECTOR_NAME VARCHAR(50) NOT NULL,
  UNI_ADDRESS VARCHAR(500) NULL,
  UNI_PHONE VARCHAR(15) NULL,
  CONSTRAINT PK_UNIVERSITY PRIMARY KEY (UNI_ID)
);
GO

CREATE TABLE dbo.SUPERVISOR(
  S_ID INT IDENTITY(1,1) NOT NULL,
  S_NAME VARCHAR(50) NOT NULL,
  CONSTRAINT PK_SUPERVISOR PRIMARY KEY (S_ID)
);
GO

/* ========== CHILD TABLOLAR ========== */

CREATE TABLE dbo.INSTITUTE(
  INS_ID INT IDENTITY(1,1) NOT NULL,
  INS_NAME VARCHAR(100) NOT NULL,
  INS_DEANNAME VARCHAR(50) NOT NULL,
  UNI_ID INT NOT NULL,
  CONSTRAINT PK_INSTITUTE PRIMARY KEY (INS_ID),
  CONSTRAINT FK_INSTITUTE_UNI FOREIGN KEY (UNI_ID)
    REFERENCES dbo.UNIVERSITY(UNI_ID)
);
GO

CREATE TABLE dbo.THESIS(
  T_NO INT IDENTITY(1,1) NOT NULL,
  T_TITLE VARCHAR(500) NOT NULL,
  T_ABSTRACT VARCHAR(5000) NULL,
  T_TOPIC VARCHAR(100) NOT NULL,
  T_KEYWORD VARCHAR(50) NULL,
  T_YEAR INT NOT NULL,
  T_TYPE VARCHAR(50) NOT NULL,
  T_INSTITUTE VARCHAR(100) NOT NULL,
  T_PAGE INT NOT NULL,
  T_LANGUAGE VARCHAR(30) NOT NULL,
  T_SUBDATE DATE NOT NULL,
  A_ID INT NOT NULL,
  UNI_ID INT NOT NULL,
  S_ID INT NOT NULL,

  CONSTRAINT PK_THESIS PRIMARY KEY (T_NO),

  CONSTRAINT FK_THESIS_AUTHOR FOREIGN KEY (A_ID)
    REFERENCES dbo.AUTHOR(A_ID),

  CONSTRAINT FK_THESIS_UNI FOREIGN KEY (UNI_ID)
    REFERENCES dbo.UNIVERSITY(UNI_ID),

  CONSTRAINT FK_THESIS_SUPERVISOR FOREIGN KEY (S_ID)
    REFERENCES dbo.SUPERVISOR(S_ID)
);
GO
